### ISSUE TITLE
Import matrix from exported file does not work

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#12]
* Release number or git hash: 64855d9b892faa39dea2694831c0b0ad50da369a
 * Web browser version and OS: Chrome 67.0.3396.62 (Offizieller Build) beta (64-Bit)

### Steps to reproduce

 1. Open https://lineup.js.org/app/#soccer
 2. Download CSV
 3. Go to dataset selection
 4. Import the saved file

### Observed behavior

Original Demo

![grafik](https://user-images.githubusercontent.com/5851088/40720516-4dda2534-6417-11e8-9fbd-bcb3cb2a8633.png)

Imported CSV file

![grafik](https://user-images.githubusercontent.com/5851088/40720537-617c17d2-6417-11e8-8631-0a03fb0033c1.png)

### Expected behavior
 * Matrix column should be parsed correctly and visualized as matrix again

**Comment by thinkh** [comment]
This issue might be related to https://github.com/datavisyn/lineup_app/issues/5

**Comment by sgratzl** [comment]
subset of the bigger #8 issue
