### ISSUE TITLE
Import CSV throws an error for `category = null`

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#13]
* Release number or git hash: fa7bad41de85361502536f9639c3ad2329376ebd
 * Web browser version and OS: Chrome 67.0.3396.62 (Offizieller Build) beta (64-Bit)

### Steps to reproduce

 1. Open https://lineup.js.org/app/#soccer
 2. Download CSV
 3. Go to dataset selection
 4. Import the saved file

### Observed behavior

Error in console (online)

![grafik](https://user-images.githubusercontent.com/5851088/40720692-de943114-6417-11e8-9b96-760ab5472da5.png)

Error in debugger (local)

![grafik](https://user-images.githubusercontent.com/5851088/40720792-2cb354f6-6418-11e8-96fd-6fe78f38af95.png)

### Expected behavior
 * `categories === null` should be ignored

**Comment by thinkh** [comment]
This is probably a LineUp issue and should be moved to [datavisyn/lineupjs](https://github.com/datavisyn/lineupjs).

**Comment by sgratzl** [comment]
fixed with https://github.com/datavisyn/lineupjs/commit/2011388c02e80bc3e77512e49ad3fca61f2e3ea9
