### ISSUE TITLE
Export CSV does not consider initial custom ranking

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#14]
* Release number or git hash: https://github.com/thinkh/lineup_app/commit/63796c6a127a0f139bdb23c3975059004ac163db
 * Web browser version and OS: Chrome 67.0.3396.62 (Offizieller Build) beta (64-Bit)

### Steps to reproduce

 1. Clone https://github.com/thinkh/lineup_app/blob/taggle_user_study
 1. Run Lineup
 1. Export CSV file

### Observed behavior
 * The exported CSV contains all columns, even though [the dataset shows only selected columns](https://github.com/thinkh/lineup_app/blob/taggle_user_study/src/data/soccer/index.ts#L85-L93) (instead of using `allColumns()`)
 * After a user interaction (e.g., filter) the export is correct

### Expected behavior
 * The export should consider initial custom ranking

This issue might be related to #7.

**Comment by sgratzl** [comment]
cannot reproduce with https://lineup.js.org/app_develop/#soccer
