### ISSUE TITLE
Select filters (in filter dialog) for categorical columns does not work

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#16]
* Release number or git hash: https://www.npmjs.com/package/lineupjs/v/3.0.1-beta.12
 * Web browser version and OS: Chrome 67 beta

### Steps to reproduce

 1. Open https://lineup.js.org/app/#soccer
 1. Click on filter icon for a categorical column
 1. Uncheck the first check mark
 1. Try to check selected categories

### Observed behavior

* Unable to check/uncheck filter
* The first two rows should do the same, don't they?

![lineup-filter-category-dialog](https://user-images.githubusercontent.com/5851088/40722837-b55d787c-641d-11e8-8f24-3577be501d4f.gif)

### Expected behavior
 * Remove the first row and keep *Un/Select All* or add a label to the first row
 * Check/uncheck categories should work

**Comment by thinkh** [comment]
@sgratzl Can you please have a look for a fix? We need this functionality for the user study.

**Comment by sgratzl** [comment]
part of 
https://github.com/datavisyn/lineup_app/commit/be48b6844256fc7b4acb6e3fb174231479794be9
https://github.com/datavisyn/lineupjs/commit/a8e7b3338a5cad93cad84ab2f6e349c736786b6e

**Comment by thinkh** [comment]
Thanks. 👍
