### ISSUE TITLE
Use colors of original LineUp

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#17]
Coming from https://github.com/Caleydo/lineupjs/issues/65 and https://github.com/Caleydo/lineup/issues/7

I don't where to find the original color scale other than this [paper figure](http://data.caleydo.org/papers/2013_infovis_lineup.pdf):

![image](https://user-images.githubusercontent.com/5851088/41284417-8410f412-6e39-11e8-9317-a5d77c084e9c.png)

**Comment by sgratzl** [comment]
why should we use these colors?

**Comment by thinkh** [comment]
Nostalgia. :)
