### ISSUE TITLE
Import does not load previously exported dataset

### ISSUE THREAD

**Issue by sgratzl** [lineupjs/lineup_app#31]
@mstreit commented on [Fri Oct 12 2018](https://github.com/datavisyn/lineupjs/issues/83)

 * Release number or git hash: public soccer demo
 * Web browser version and OS: Chrome

### Steps to reproduce

 1. Open soccer dataset
 2. Export CSV
 3. Import the previously exported CSV

Similar problems when exporting and importing JSON.

### Observed behavior
 * Only loading bar is shown

### Expected behavior
 * Dataset should appear in LineUp

**Comment by mstreit** [comment]
Might be related to #12 and #13.

**Comment by sgratzl** [comment]
loads except #12
