### ISSUE TITLE
Fix alignment of `Group by` dialog for numerical columns

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#37]
* Release number or git hash: v4.0.0-alpha.8
 * Web browser version and OS: Chrome 71-beta

### Steps to reproduce

 1. Select a numerical column
 1. Open `Group by` dialog

### Observed behavior

![image](https://user-images.githubusercontent.com/5851088/49027077-aa0ef080-f19f-11e8-87ae-6a3058dc4be6.png)

### Expected behavior
 * Alignment should be correct. The buttons at the bottom of the dialog should be visible.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/50684121-b5620100-1014-11e9-919d-db5c56e2ecd9.png)
