### ISSUE TITLE
Sidebar does not close fully

### ISSUE THREAD

**Issue by zichner** [lineupjs/lineup_app#41]
* Release number or git hash: version deployed at https://taggle.caleydoapp.org
 * Web browser version and OS: Chrome

### Steps to reproduce

 1. Open any LineUp ranking
 2. Close side bar on the right

-> Selection `Item vs Overview` is still visible

**Comment by sgratzl** [comment]
cannot reproduce

![sidebar](https://user-images.githubusercontent.com/4129778/131348558-54f0d8c6-9a04-4d28-8bba-77c3e22747ce.gif)
