### ISSUE TITLE
Remove MatrixColumn again?

### ISSUE THREAD

**Issue by sgratzl** [lineupjs/lineup_app#54]
https://github.com/lineupjs/lineup_app/blob/develop/src/model/MatrixColumn.ts

IMO, the lineup_app should just show and use features that are provided by the library thus not extending LineUp itself cause it will break among others all export functionalities.

**Comment by thinkh** [comment]
I agree... Same problem as always with the Github resolve conflicts. I'll revert this commit.

**Comment by thinkh** [comment]
Fixed by force pushing the old commit again.
