### ISSUE TITLE
Broken export to CodeSandbox 

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineup_app#67]
* Release number or git hash: 4.0.0
 * Web browser version and OS: Chrome 87

### Steps to reproduce

 1. Open https://lineup.js.org/app_develop/#soccer
 1. Export to example to CodeSandbox.io

#### Error 1

```
DependencyNotFoundError
Could not find dependency: 'tslib' relative to '/node_modules/lineupjs/src/provider/ADataProvider.js'
```

![grafik](https://user-images.githubusercontent.com/5851088/102491833-14d64180-4071-11eb-9a78-7b3203b277bd.png)

If I follow the instructions and import tslib, I get the following error.

#### Error 2

```
TypeError
Cannot read property 'FLOAT_ASC' of undefined

...

  1 | 
> 2 | import * as LineUpJS from "lineupjs";
  3 | import "lineupjs/build/LineUpJS.css";
  4 | import * as Papa from "papaparse";
  5 | 
```

![grafik](https://user-images.githubusercontent.com/5851088/102491950-3e8f6880-4071-11eb-8296-f20866494fef.png)

Switching the dependency to LineUp v4.1.1 shows the same error.

![grafik](https://user-images.githubusercontent.com/5851088/102492123-7d252300-4071-11eb-8219-fad6b7c25965.png)

### Expected behavior

The export should work without errors and show the demo.

**Comment by sgratzl** [comment]
the dev version of lineupjs (lineupjs@next) should have no problems anymore with circular imports

**Comment by dg-datavisyn** [comment]
I still have the issue with the version 4.2.0-alpha.1 which is labelled as next on npmjs.
See https://codesandbox.io/s/lineup-boiler-plate-pktp1?file=/package.json
