### ISSUE TITLE
Cannot npm start/build after npm install: node_modules/@babel/compat-data/data/corejs3-shipped-proposals

### ISSUE THREAD

**Issue by heberleh** [lineupjs/lineup_app#91]
Error: Cannot find module '... /lineup_app/node_modules/@babel/compat-data/data/corejs3-shipped-proposals'

After cloning and `npm install`, the `npm start` and `npm build` give this error.

**Comment by heberleh** [comment]
After deleting package.lock and node_modules, to try to force an update, `npm install` gave this error:

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: lineup_app@4.0.0
> npm ERR! Found: tslint@6.1.3
> npm ERR! node_modules/tslint
> npm ERR!   dev tslint@"^6.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer tslint@"^5.0.0" from tslint-consistent-codestyle@1.16.0
> npm ERR! node_modules/tslint-consistent-codestyle
> npm ERR!   dev tslint-consistent-codestyle@"^1.16.0" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by heberleh** [comment]
```
sudo npm update --depth 5 @babel/preset-env
sudo npm update --depth 5 @babel/compat-data
```
locally 'solved the problem'

**Comment by sgratzl** [comment]
this project is optimized in using https://yarnpkg.com/

**Comment by heberleh** [comment]
README points user to use `npm`

**Comment by sgratzl** [comment]
in the development branch it correctly points to yarn: https://github.com/lineupjs/lineup_app/tree/develop#development-environment
