### ISSUE TITLE
Grouping not working

### ISSUE THREAD

**Issue by heberleh** [lineupjs/lineup_app#92]
After uploading a csv and trying to group, the menu doesn't apply the grouping. Clicking 'confirm' doesn't close the menu.
Clicking outside the menu will make the grouping to be removed.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/4249107/167139263-e5540a91-335f-4c06-94da-e1b494671cfe.png">

Clicking on 'confirm' returns error:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/4249107/167139361-44d7025f-8b91-43d5-90a6-1d3fa517f1cb.png">

Reproduced with selecting an internal dataset from the homepage.

The problem seems to happen with this type of column:
<img width="56" alt="image" src="https://user-images.githubusercontent.com/4249107/167142425-2ad6fdaa-daf3-4a3e-85b5-f0e5a0219c90.png">

It actually groups, but then it ungroup because the confirm button doesn't work.

**Comment by heberleh** [comment]
This happened in Chrome Version 100.0.4896.127 (Official Build) (x86_64)
Tried in Edge and it worked.

**Comment by sgratzl** [comment]
cannot reproduce anymore in https://lineup.js.org/app/#simple
